debug: true

database:
  type: JSON

cosmetics:
  quest_increment:
    action_bar:
      enabled: true
      message: "&e%quest_name% &8| &e%task_progress%/%task_required%"
    titles:
      enabled: false
      title: ""
      subtitle: ""
  quest_done:
    action_bar:
      enabled: false
      message: ""
    titles:
      enabled: true
      title: "&aCongratulations !"
      subtitle: "&aYou have just finished the quest: %quest_name%"
