debug: true

database:
  type: JSON
  mariadb:
    host: "localhost"
    port: 3306
    database: "quest"
    username: "user"
    password: "password"

cosmetics:
  task_increment:
    action_bar:
      enabled: true
      message: "&e%quest_name% &8| &e%task_progress%/%task_required%"
    titles:
      enabled: false
      title: ""
      subtitle: ""
  task_done:
    action_bar:
      enabled: true
      message: "&a%quest_name% &8| &e&lCOMPLETED"
    titles:
      enabled: true
      title: "&aTask completed !"
      subtitle: "&aYou have just finished a task for the quest: %quest_name%"
  quest_done:
    action_bar:
      enabled: false
      message: ""
    titles:
      enabled: true
      title: "&aCongratulations !"
      subtitle: "&aYou have just finished the quest: %quest_name%"

time_format:
  days: "d"
  hours: "h"
  minutes: "m"
  seconds: "s"
  format: "%days%%hours%%minutes%%seconds%"